"""Initial migration with clean schema

Revision ID: 8d670c3c8a6d
Revises: 
Create Date: 2026-05-22 14:24:21.077379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d670c3c8a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_reports_predicted_risk'), ['predicted_risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_reports_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_reports_verified'), ['verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_reports_village'), ['village'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('email_2'))
        batch_op.drop_index(batch_op.f('phone'))
        batch_op.drop_index(batch_op.f('phone_2'))
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('water_quality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_quality_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_quality_recorded_year'), ['recorded_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_quality_village'), ['village'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_quality_water_quality_index'), ['water_quality_index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_quality', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_quality_water_quality_index'))
        batch_op.drop_index(batch_op.f('ix_water_quality_village'))
        batch_op.drop_index(batch_op.f('ix_water_quality_recorded_year'))
        batch_op.drop_index(batch_op.f('ix_water_quality_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_district'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_index(batch_op.f('phone_2'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('email_2'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('symptom_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_reports_village'))
        batch_op.drop_index(batch_op.f('ix_symptom_reports_verified'))
        batch_op.drop_index(batch_op.f('ix_symptom_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_reports_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_symptom_reports_predicted_risk'))

    # ### end Alembic commands ###
